name: ci.yml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ['1.26.0']
        golangci-lint-version: ['2.9.0']

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go version

      - name: Install golangci-lint
        run: |
            curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v${{ matrix.golangci-lint-version }}
            golangci-lint --version
      - name: Build loglint plugin
        run: |
            golangci-lint custom -v
      - name: Run linter
        run: |
          ./bin/loglint run -v ./
      - name: Testing
        run: |
          go test ./...
